---
- name: Install Java 17
  ansible.builtin.yum:
    name: java-17-amazon-corretto
    state: present
  become: true

- name: Add Jenkins repository
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
  become: true

- name: Import Jenkins GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
  become: true

- name: Install Jenkins
  ansible.builtin.yum:
    name: jenkins
    state: present
  become: true

- name: Enable and start Jenkins
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: true
  become: true
