---
- name: Download kubectl
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
  become: true

- name: Verify kubectl installation
  ansible.builtin.command: kubectl version --client
  register: kubectl_version

- name: Show kubectl version
  ansible.builtin.debug:
    var: kubectl_version.stdout

