apiVersion: v1
kind: Service
metadata:
  name: cloud-devops-service
  namespace: ivolve
spec:
  selector:
    app: cloud-devops-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: ClusterIP

