apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-devops-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/hishamatwa/CloudDevOpsProject.git
    targetRevision: main
    path: kubernetes/base

  destination:
    server: https://kubernetes.default.svc
    namespace: ivolve

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

