pipeline {
    agent any

    environment {
        IMAGE_NAME = "cloud-devops-app"
        IMAGE_TAG = "${BUILD_NUMBER}"

        AWS_ACCESS_KEY_ID = credentials('aws-access-key')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')

        AWS_REGION = "eu-north-1"
        ECR_REPOSITORY = "cloud-devops-app"
        ECR_REGISTRY = "889007427509.dkr.ecr.eu-north-1.amazonaws.com"
        REPOSITORY_URI = "${ECR_REGISTRY}/${ECR_REPOSITORY}"
    }

    stages {
        stage('Build Image') {
            steps {
                sh """
                    docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -f docker/Dockerfile .
                """
            }
        }

        stage('Scan Image') {
            steps {
                sh """
                    trivy image ${IMAGE_NAME}:${IMAGE_TAG} || true
                """
            }
        }

        stage('Push Image') {
            steps {
                sh """
                    aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
                    docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${REPOSITORY_URI}:${IMAGE_TAG}
                    docker push ${REPOSITORY_URI}:${IMAGE_TAG}
                """
            }
        }

        stage('Delete Image Locally') {
            steps {
                sh """
                    docker rmi ${IMAGE_NAME}:${IMAGE_TAG} || true
                    docker rmi ${REPOSITORY_URI}:${IMAGE_TAG} || true
                """
            }
        }

        stage('Update Manifests') {
            steps {
                sh """
                    sed -i 's|image: .*|image: ${REPOSITORY_URI}:${IMAGE_TAG}|g' kubernetes/base/deployment.yaml
                """
            }
        }

        stage('Push Manifests') {
            steps {
                sh """
                    git config user.email "jenkins@example.com"
                    git config user.name "Jenkins CI"
                    git add kubernetes/base/deployment.yaml
                    git commit -m "ci: update deployment image to ${IMAGE_TAG}" || true
                    git push origin HEAD:main || true
                """
            }
        }
    }
}
