pipeline {
    agent any

    environment {
        IMAGE_NAME = "cloud-devops-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
        AWS_REGION = "eu-north-1"
        ECR_REPOSITORY = "cloud-devops-app" 
        ECR_REGISTRY = "889007427509.dkr.ecr.eu-north-1.amazonaws.com"
        REPOSITORY_URI = "${ECR_REGISTRY}/${ECR_REPOSITORY}"
    }

    stages {
        stage('Build Image') {
            steps {
                script {
                    dockerBuild(env.IMAGE_NAME, env.IMAGE_TAG)
                }
            }
        }

        stage('Scan Image') {
            steps {
                script {
                    trivyScan(env.IMAGE_NAME, env.IMAGE_TAG)
                }
            }
        }

        stage('Push Image') {
            steps {
                sh """
                    aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
                """
                script {
                    dockerPush(env.IMAGE_NAME, env.IMAGE_TAG, env.REPOSITORY_URI)
                }
            }
        }

        stage('Delete Image Locally') {
            steps {
                script {
                    dockerCleanup(env.IMAGE_NAME, env.IMAGE_TAG, env.REPOSITORY_URI)
                }
            }
        }

        stage('Update Manifests') {
            steps {
                sh """
                    sed -i 's|image: .*|image: ${REPOSITORY_URI}:${IMAGE_TAG}|g' kubernetes/base/deployment.yaml
                """
            }
        }

        stage('Push Manifests') {
            steps {
                sh """
                    git config user.email "jenkins@example.com"
                    git config user.name "Jenkins CI"
                    git add kubernetes/base/deployment.yaml
                    git commit -m "ci: update deployment image to ${IMAGE_TAG}" || true
                    git push origin main
                """
            }
        }
    }
}
